### Get menu items
GET http://localhost:8080/api/menu

### Create a cart
POST http://localhost:8080/api/cart
Content-Type: application/json

{
  "items": [
    {
      "item": {
        "id": "p-magaritha",
        "name": "Pizza Margherita",
        "description": "A classic Italian masterpiece featuring a thin, crispy crust topped with rich tomato sauce, fresh mozzarella, and aromatic basil leaves. Simple, yet bursting with authentic flavors.",
        "price": 10.0
      },
      "amount": 2
    },
    {
      "item": {
        "id": "p-hawaiian",
        "name": "Hawaiian Pizza",
        "description": "Pineapple, ham, and mozzarella—because some pizzas just want to watch the world debate. Love it or leave it, this tropical twist is a slice of sweet rebellion.",
        "price": 4.2
      },
      "amount": 1
    }
  ]
}