site_name: FluxFlow
theme:
  name: readthedocs
  logo: assets/condensed-white-transparent-200.png
  highlightjs: true
  hljs_languages:
    - yaml
    - java
    - kotlin
extra_css:
  - style.css
nav:
  - Home: index.md
  - API Objects:
    - Steps: steps.md
    - Jobs: jobs.md
  - Features:
    - Automation: automation.md
    - Injection: injection.md
    - Validation: validation.md
    - Queries: queries.md
  - Other resources:
    - Sources: https://github.com/lisegmbh/fluxflow
    - Issues: https://github.com/lisegmbh/fluxflow/issues
