site_name: FluxFlow
theme:
  name: readthedocs
  logo: assets/condensed-white-transparent-200.png
  highlightjs: true
  hljs_languages:
    - yaml
    - java
    - kotlin
extra_css:
  - style.css
markdown_extensions:
  - admonition
nav:
  - Home: index.md
  - Getting started: getting-started/getting-started.md
  - API Objects:
    - Workflows:
      - Basics: workflow/basics.md
      - Model: workflow/model.md
    - Steps: steps.md
    - Jobs: jobs.md
  - Features:
    - Automation: features/automation.md
    - Injection: features/injection.md
    - Validation: features/validation.md
    - Versioning: features/versioning.md
    - Queries: features/queries.md
  - Spring:
    - Settings: spring/settings.md
  - Migration guides:
    - v0.2.0: migrations/v0.2.0.md
  - Other resources:
    - Sources: https://github.com/lisegmbh/fluxflow
    - Issues: https://github.com/lisegmbh/fluxflow/issues
    - Changelog: https://github.com/lisegmbh/fluxflow/blob/main/CHANGELOG.md
