site_name: FluxFlow
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - java
    - kotlin
extra_css:
  - style.css
nav:
  - Home: index.md
  - Steps: steps.md
  - Jobs: jobs.md