plugins {
	id("org.springframework.boot") version "3.2.3"
	id("io.spring.dependency-management") version "1.1.4"
	kotlin("jvm") version "2.2.0"
	kotlin("plugin.spring") version "1.9.22"
}

group = "de.lise.fluxflow.examples"
version = "0.1.0-SNAPSHOT"

java {
	sourceCompatibility = JavaVersion.VERSION_17
}

repositories {
	mavenCentral()
}

dependencies {
	// Fluxflow dependencies
	implementation("de.lise.fluxflow:springboot-spring3:0.3.0") // Core dependency
	// implementation("de.lise.fluxflow:springboot-mongo-spring3:0.3.0") // FluxFlow MongoDB persistence support
	implementation("de.lise.fluxflow:springboot-in-memory-persistence:0.2.0") // FluxFlow In-memory persistence
	implementation("de.lise.fluxflow:springboot-web:0.2.0") // FluxFlow support for springboot-web projects

	// Spring Boot dependencies as generated by the Spring Initializr
	implementation("org.springframework.boot:spring-boot-starter-data-mongodb")
	implementation("org.springframework.boot:spring-boot-starter-web")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("org.jetbrains.kotlin:kotlin-reflect")

	// Test dependencies (also generated by the Spring Intializr)
	testImplementation("org.springframework.boot:spring-boot-starter-test")
}

tasks.withType<Test> {
	useJUnitPlatform()
}
