#### 1. Create new workflow
POST {{api}}/idea

### Get workflows
GET {{api}}/workflow

### Get single workflow
GET {{api}}/workflow/0

### Get workflow steps
GET {{api}}/workflow/0/step

### Get workflow steps with filter
GET {{api}}/workflow/0/step?$filter=contains(metadata/kind, 'SubmitIdeaStep') and metadata/annotations/starter eq true and spec/data/non-existing eq null and status/status eq 'Active'

### Get single workflow step
GET {{api}}/workflow/0/step/1

### Get all workflow step data
GET {{api}}/workflow/0/step/1/data

### Get single workflow step data
GET {{api}}/workflow/0/step/1/data/author

### Patch single workflow step data
PATCH {{api}}/workflow/0/step/1/data/author
Content-Type: application/json

[
  {
    "op": "replace",
    "path": "/value",
    "value": "Erica Example"
  }
]


### Get single workflow step data's value
GET {{api}}/workflow/0/step/1/data/author/value

### Set single workflow step data's value
PUT {{api}}/workflow/0/step/1/data/author/value
Content-Type: application/json

"Max Mustermann"

### Delete by id
DELETE {{api}}/workflow/0